service: shmenkins2

frameworkVersion: ">=1.26.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

provider:
  name: aws
  profile: ${self:service}
  region: us-west-2
  runtime: python3.6
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: ${self:custom.build_requested_topic_arn}

custom:
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:service}-${self:custom.stage}
  build_requested_topic: ${self:custom.prefix}-build_requested
  # arn:aws:sns:us-west-2:000000000000:shmenkins2-dev-build_requested
  build_requested_topic_arn: arn:aws:sns:${self:provider.region}:#{AWS::AccountId}:${self:custom.build_requested_topic}

package:
  exclude:
    - "**/*"
  include:
    - "shmenkins2/*"

functions:

  HandlePushNotification:
    handler: shmenkins2/HandlePushNotification.run
    events:
      - http: POST push-notifications
    environment:
      BUILD_REQUESTED_TOPIC_ARN: ${self:custom.build_requested_topic_arn}

  ScheduleBuild:
    handler: shmenkins2/ScheduleBuild.run
    events:
      - sns: ${self:custom.build_requested_topic}
