service: shmenkins2

frameworkVersion: ">=1.26.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

provider:
  name: aws
  profile: ${self:service}
  region: us-west-2
  runtime: python3.6
  memorySize: 128
  iamRoleStatements:

    - Effect: Allow
      Action:
        - sns:Publish
      Resource: ${self:custom.build_requested_topic_arn}

    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource: ${self:custom.default_build_queue_arn}

custom:
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:service}-${self:custom.stage}

  build_requested_topic: ${self:custom.prefix}-build_requested
  build_requested_topic_arn: arn:aws:sns:${self:provider.region}:#{AWS::AccountId}:${self:custom.build_requested_topic}

  build_scheduled_topic: ${self:custom.prefix}-build_scheduled
  build_scheduled_topic_arn: arn:aws:sns:${self:provider.region}:#{AWS::AccountId}:${self:custom.build_scheduled_topic}

  default_build_queue: ${self:custom.prefix}-default_build_queue
  default_build_queue_arn: arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:${self:custom.default_build_queue}

package:
  exclude:
    - "**/*"
  include:
    - "shmenkins2/*"

functions:

  LogSnsEvent:
    handler: shmenkins2/LogSnsEvent.run
    events:
      - sns: ${self:custom.build_requested_topic}
      - sns: ${self:custom.build_scheduled_topic}

  HandlePushNotification:
    handler: shmenkins2/HandlePushNotification.run
    events:
      - http: POST push-notifications
    environment:
      BUILD_REQUESTED_TOPIC_ARN: ${self:custom.build_requested_topic_arn}

  ScheduleBuild:
    handler: shmenkins2/ScheduleBuild.run
    events:
      - sns: ${self:custom.build_requested_topic}
    environment:
      BUILD_SCHEDULED_TOPIC_ARN: ${self:custom.build_scheduled_topic_arn}

resources:
  Resources:

    DefaultBuildQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.default_build_queue}
