service: shmenkins2

frameworkVersion: ">=1.26.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

provider:
  name: aws
  profile: shmenkins2
  region: us-west-2
  runtime: python3.6
  memorySize: 128
  environment:
    RESOURCE_PREFIX: ${self:custom.prefix}

  iamRoleStatements:

    - Effect: Allow
      Action:
        - sns:Publish
      Resource: ${self:custom.build_requested_topic_arn}

    - Effect: Allow
      Action:
        - sns:Publish
      Resource: ${self:custom.build_scheduled_topic_arn}

    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource: ${self:custom.default_build_queue_arn}

    - Effect: Allow
      Action:
        - iam:PassRole
        - codebuild:CreateProject
        - codebuild:UpdateProject
      Resource: "*"

custom:
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:service}-${self:custom.stage}

  build_requested_topic: ${self:custom.prefix}-build_requested
  build_requested_topic_arn: arn:aws:sns:${self:provider.region}:#{AWS::AccountId}:${self:custom.build_requested_topic}

  build_scheduled_topic: ${self:custom.prefix}-build_scheduled
  build_scheduled_topic_arn: arn:aws:sns:${self:provider.region}:#{AWS::AccountId}:${self:custom.build_scheduled_topic}

  default_build_queue: ${self:custom.prefix}-default_build_queue
  default_build_queue_arn: arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:${self:custom.default_build_queue}

  cb_service_role: ${self:custom.prefix}-cb_service_role
  cb_service_role_arn: arn:aws:iam::#{AWS::AccountId}:role/${self:custom.cb_service_role}

package:
  exclude:
    - "**/*"
  include:
    - "shmenkins2/*"

functions:

  LogSnsEvent:
    handler: shmenkins2/LogSnsEvent.run
    events:
      - sns: ${self:custom.build_requested_topic}
      - sns: ${self:custom.build_scheduled_topic}

  HandlePushNotification:
    handler: shmenkins2/HandlePushNotification.run
    events:
      - http: POST push-notifications
    environment:
      BUILD_REQUESTED_TOPIC_ARN: ${self:custom.build_requested_topic_arn}

  ScheduleBuild:
    handler: shmenkins2/ScheduleBuild.run
    events:
      - sns: ${self:custom.build_requested_topic}
    environment:
      BUILD_SCHEDULED_TOPIC_ARN: ${self:custom.build_scheduled_topic_arn}

  BuildWithAwsCb:
    handler: shmenkins2/BuildWithAwsCb.run
    events:
      - sns: ${self:custom.build_scheduled_topic}
    environment:
      CB_SERVICE_ROLE_ARN: ${self:custom.cb_service_role_arn}

  PostScmTrigger:
    handler: shmenkins2/PostScmTrigger.run
    events:
      - http: POST scm-triggers
    environment:
      DB_URL: mysql+mysqlconnector://shmenkins:${ssm:/shmenkins_password}@${ssm:/shmenkins_db_endpoint}/shmenkins

resources:
  Resources:

    DefaultBuildQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.default_build_queue}

    CbServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.cb_service_role}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: codebuild.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AllowLogging
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"

    MainDbMasterUserPasswordParameter:
      Type: "AWS::SSM::Parameter"
      Properties:
        Name: shmenkins_api_url
        Type: String
        Value:
          Fn::Join:
            - ""
            - - "https://"
              - Ref: ApiGatewayRestApi
              - ".execute-api.${self:provider.region}."
              - Ref: "AWS::URLSuffix"
              - "/"
              - ${self:custom.stage}
