vpc:
	sceptre --var-file variables.yaml launch-stack dev vpc

rds:
	sceptre --var-file variables.yaml launch-stack dev rds

ssm:
	sceptre --var-file variables.yaml launch-stack dev ssm

cb:
	sceptre --var-file variables.yaml launch-stack dev cb
