AWSTemplateFormatVersion: 2010-09-09

Description: RDS MySQL DB

Parameters:
    MainDbMasterUserPassword:
      Type: "AWS::SSM::Parameter::Value<String>"
      Default: main_db_password

Resources:
  MyDB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      Engine: MySQL
      EngineVersion: 5.7.21
      AllowMajorVersionUpgrade: true
      MasterUsername: master
      MasterUserPassword: !Ref MainDbMasterUserPassword
