AWSTemplateFormatVersion: 2010-09-09

Description: RDS MySQL DB

Parameters:
    MainDbMasterUserPassword:
      Type: "AWS::SSM::Parameter::Value<String>"
      Default: main_db_password

Resources:
  RDSDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: shmenkins DB parameter group
      Family: MySQL5.7
      #Parameters:
      Tags:
        - Key: Name
          Value: shmenkins

  MyDB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      Engine: MySQL
      EngineVersion: 5.7.21
      AllowMajorVersionUpgrade: true
      MasterUsername: master
      MasterUserPassword: !Ref MainDbMasterUserPassword
      DBParameterGroupName: !Ref RDSDBParameterGroup
