AWSTemplateFormatVersion: 2010-09-09

Description: RDS MySQL DB

Parameters:
    MainDbMasterUserPassword:
      Type: "AWS::SSM::Parameter::Value<String>"
      Default: main_db_password
    UsWest2VPC:
      Type: String
    UsWest2APublicSubnet:
      Type: String
    UsWest2BPublicSubnet:
      Type: String
    UsWest2CPublicSubnet:
      Type: String

Resources:
  RDSDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: shmenkins DB parameter group
      Family: MySQL5.7
      #Parameters:
      Tags:
        - Key: Name
          Value: shmenkins

  UsWest2APublicSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: Shmenkins us-west-2a public subnet group
      SubnetIds:
        - !Ref UsWest2APublicSubnet
        - !Ref UsWest2BPublicSubnet
        - !Ref UsWest2CPublicSubnet
      Tags:
        - Key: Name
          Value: shmenkins

  MyDB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      Engine: MySQL
      EngineVersion: 5.7.21
      AllowMajorVersionUpgrade: true
      MasterUsername: master
      MasterUserPassword: !Ref MainDbMasterUserPassword
      DBParameterGroupName: !Ref RDSDBParameterGroup
      DBSubnetGroupName: !Ref UsWest2APublicSubnetGroup
      VPCSecurityGroups: [!Ref DBSecurityGroup]
      PubliclyAccessible: true
      Tags:
        - Key: Name
          Value: shmenkins

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow mysql client from internet
      VpcId: !Ref UsWest2VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  ShmenkinsDBEndpointParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: shmenkins_db_endpoint
      Type: String
      Value: !GetAtt MyDB.Endpoint.Address

Outputs:
  ShmenkinsDBEndpoint:
    Description: The shmenkins db endpoint url
    Value: !GetAtt MyDB.Endpoint.Address
    Export:
      Name: "endpoint"
