AWSTemplateFormatVersion: 2010-09-09

Description: Various parameters

Parameters:
  MainDbMasterUserPassword:
    Type: String
    Description: Master user password for the main database
    NoEcho: true
  DbUserShmenkinsAdminPassword:
    Type: String
    Description: Admin user password for the shmenkins database
    NoEcho: true
  DbUserShmenkinsPassword:
    Type: String
    Description: App user password for the shmenkins database
    NoEcho: true
  CodePipelineGitHubAccessToken:
    Type: String
    Description: Personal access token used to access GitHub API
    NoEcho: true

Resources:
  MainDbMasterUserPasswordParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: main_db_password
      Type: String
      Value: !Ref MainDbMasterUserPassword
  ShmenkinsAdminPasswordParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: shmenkins_admin_password
      Type: String
      Value: !Ref DbUserShmenkinsAdminPassword
  ShmenkinsPasswordParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: shmenkins_password
      Type: String
      Value: !Ref DbUserShmenkinsPassword
  CodePipelineGitHubAccessTokenParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: code_pipeline_github_access_token
      Type: String
      Value: !Ref CodePipelineGitHubAccessToken
