AWSTemplateFormatVersion: 2010-09-09
Description: RDS MySQL DB
Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 1
      Engine: MySQL
      MasterUsername: master
      MasterUserPassword:
