AWSTemplateFormatVersion: 2010-09-09

Description: Various parameters

Parameters:
  MainDbMasterUserPassword:
    Type: String
    Description: Master user password for the main database
    NoEcho: true

Resources:
  MainDbMasterUserPasswordParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: main_db_password
      Type: String
      Value: !Ref MainDbMasterUserPassword
