AWSTemplateFormatVersion: 2010-09-09

Resources:

  ShmenkinsUsWest2VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16

  UsWest2APrivate:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ShmenkinsUsWest2VPC
      CidrBlock: 10.0.0.0/19
      AvailabilityZone: "us-west-2a"
      Tags:
        - Key: Name
          Value: us-west-2a private

  UsWest2APublic:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ShmenkinsUsWest2VPC
      CidrBlock: 10.0.32.0/20
      AvailabilityZone: "us-west-2a"
      Tags:
        - Key: Name
          Value: us-west-2a public

  UsWest2ASpare:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ShmenkinsUsWest2VPC
      CidrBlock: 10.0.48.0/20
      AvailabilityZone: "us-west-2a"
      Tags:
        - Key: Name
          Value: us-west-2a spare

  UsWest2BPrivate:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ShmenkinsUsWest2VPC
      CidrBlock: 10.0.64.0/19
      AvailabilityZone: "us-west-2b"
      Tags:
        - Key: Name
          Value: us-west-2b private

  UsWest2BPublic:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ShmenkinsUsWest2VPC
      CidrBlock: 10.0.96.0/20
      AvailabilityZone: "us-west-2b"
      Tags:
        - Key: Name
          Value: us-west-2b public

  UsWest2BSpare:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ShmenkinsUsWest2VPC
      CidrBlock: 10.0.112.0/20
      AvailabilityZone: "us-west-2b"
      Tags:
        - Key: Name
          Value: us-west-2b spare

  UsWest2CPrivate:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ShmenkinsUsWest2VPC
      CidrBlock: 10.0.128.0/19
      AvailabilityZone: "us-west-2c"
      Tags:
        - Key: Name
          Value: us-west-2c private

  UsWest2CPublic:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ShmenkinsUsWest2VPC
      CidrBlock: 10.0.160.0/20
      AvailabilityZone: "us-west-2c"
      Tags:
        - Key: Name
          Value: us-west-2c public

  UsWest2CSpare:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref ShmenkinsUsWest2VPC
      CidrBlock: 10.0.176.0/20
      AvailabilityZone: "us-west-2c"
      Tags:
        - Key: Name
          Value: us-west-2c spare

  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: us-west-2 shmenkins

  IGWAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref ShmenkinsUsWest2VPC

  UsWest2RouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties: 
      VpcId: !Ref ShmenkinsUsWest2VPC
      Tags:
        - Key: Name
          Value: us-west-2 shmenkins

  UsWest2PublicToInternetRoute:
    Type: "AWS::EC2::Route"
    DependsOn: InternetGateway
    Properties:
      RouteTableId: !Ref UsWest2RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  UsWest2APublicSubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref UsWest2APublic
      RouteTableId: !Ref UsWest2RouteTable

  UsWest2BPublicSubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref UsWest2BPublic
      RouteTableId: !Ref UsWest2RouteTable

  UsWest2CPublicSubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref UsWest2CPublic
      RouteTableId: !Ref UsWest2RouteTable
      
Outputs:
  ShmenkinsUsWest2VPC:
    Description: The ID of the Shmenkins us-west-2 VPC
    Value: !Ref ShmenkinsUsWest2VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"

# see https://medium.com/aws-activate-startup-blog/practical-vpc-design-8412e1a18dcc
#10.0.0.0/16:
#   10.0.0.0/18 — AZ A
#       10.0.0.0/19 — Private
#       10.0.32.0/19
#              10.0.32.0/20 — Public
#              10.0.48.0/20
#                  10.0.48.0/21 — Protected
#                  10.0.56.0/21 — Spare
#   10.0.64.0/18 — AZ B
#       10.0.64.0/19 — Private
#       10.0.96.0/19
#               10.0.96.0/20 — Public
#               10.0.112.0/20
#                   10.0.112.0/21 — Protected
#                   10.0.120.0/21 — Spare
#   10.0.128.0/18 — AZ C
#       10.0.128.0/19 — Private
#       10.0.160.0/19
#               10.0.160.0/20 — Public
#               10.0.176.0/20
#                   10.0.176.0/21 — Protected
#                   10.0.184.0/21 — Spare
#   10.0.192.0/18 — Spare
